[package]
name = "poly-core"
version = { workspace = true }
edition = { workspace = true }
repository = "https://github.com/Yrrrrrf/poly-core"
description = "One logic. A thousand faces. The unified entry point over polyglot-core's domain logic."
authors = { workspace = true }
license = { workspace = true }
readme = "README.md"
keywords = { workspace = true }
categories = ["development-tools"]

[dependencies]
polyglot-core = { path = "../core", version = "0.0.1" }
